### PR TITLE
Get content moved over from rails app

### PR DESCRIPTION
**Pull request by jayroh**
Among other setup and config things

### CODE REVIEW

**Comment by jayroh** [comment]
@dperrera there's a lot of code in here to read so I wouldn't necessarily recommend reviewing it - also, most of it is your code so that's up to you. Haha.

There *is*, however, some configuration stuff in there you might want to peek in on if you are so inclined.

I'll keep this in a holding pattern until you've gotten a second to chime in so I'm not merging it into master and causing any issues. If you were working on all this yesterday you might end up needing to rebase your latest code on top of this.

**Comment by dperrera** [comment]
I had a bit of trouble getting this puppy going. Running `gulp` failed initially. To fix it I hat to run `gulp sass; gulp js` and then `gulp` worked fine. Stopping and starting the default Gulp task seems to recreate the issue, which is a bit annoying. 

I think it's because Jekyll wants to recompile the entire `/public` directory and then our Gulp tasks want to write or overwrite files that live there but may not have the correct permissions. It seems to me that a *fast* way to fix this problem is to compile our Gulp js and sass tasks into the `src/jekyll/scripts` and `src/jekyll/styles` respectively and use `jekyll serve --watch` to do the updating but my intuition says it's not going to be that simple.

I'd love to retain our sweet build process but I wonder if it's at odds with how Jekyll works?

**Comment by jayroh** [comment]
@dperrera I had those same issues! I think this PR fixes that with the config updates.

```
rm -rf public
git checkout origin/jro-copy-content
gulp
```

And see what happens :)

**Comment by jayroh** [comment]
The jekyll problems were purely config ones. Usually jekyll retains the responsibilities that something like Gulp would, but since we're Gulp'ing it up I needed to force jekyll to do its job without stepping on our toes. In this case the literal "stepping on toes" was jekyll deleting all files that end up in public. After telling it NOT TO, things are a-ok.

See `src/jekyll/_config.yml` for `keep_files` -> https://github.com/shuboxio/site/pull/1/files#diff-9423431b12400d6b533757c649d39922R36

**Comment by dperrera** [comment]
Ok, I think I got this worked out to get up and running. Let's merge it and improve the build tools as we go!

**Comment by dperrera** [comment]
Also, do you think I can have write access for this repo? 🌝

**Comment by jayroh** [comment]
OY VEY!

**Comment by jayroh** [comment]
Merging, and just updated the settings. You should have write access now, @dperrera!

**Comment by dperrera** [comment]
@jayroh Thanks!

**Pull request merged**
